create table STUDENT
(
	STUDENT_ID INTEGER not null primary key,
	STUDENT_NAME VARCHAR(250),
	IDNUMBER NUMERIC not null,
	FIRSTNAME VARCHAR(250),
	LASTNAME VARCHAR(250),
	EMAIL VARCHAR(250),
	MODULENAME VARCHAR(250),
	INSTITUTION_ID INTEGER not null
);

CREATE SEQUENCE S_STUDENT START WITH 1 INCREMENT BY 1;



