create table FNB
(
	CARD_ID INTEGER not null primary key,
	CARD_HOLDER_NAME VARCHAR(250),
	BANK_NAME VARCHAR(250),
	CARD_NUMBER NUMERIC(13) not null,
	BALANCE NUMERIC(16) not null,
	TRANSACTIONAMOUNT NUMERIC(16) not null,
	TRANSACTIONTYPE VARCHAR(250),
	PIN_NUMBER NUMERIC(5) not null,
	CVV_NUMBER NUMERIC(3) not null	
);


INSERT INTO APP.FNB (CARD_ID, CARD_HOLDER_NAME, BANK_NAME, CARD_NUMBER, BALANCE, TRANSACTIONAMOUNT, TRANSACTIONTYPE, PIN_NUMBER, CVV_NUMBER) 
	VALUES (1, 'Tebogo', 'FNB', 123456789, 200, 0, '0', 1234, 123);
INSERT INTO APP.FNB (CARD_ID, CARD_HOLDER_NAME, BANK_NAME, CARD_NUMBER, BALANCE, TRANSACTIONAMOUNT, TRANSACTIONTYPE, PIN_NUMBER, CVV_NUMBER) 
	VALUES (2, 'Tebgo2', 'FNB', 987654321, 600, 0, '0', 1234, 123);
