
create table INSTITUTION_TYPE
(
	TYPE_ID INTEGER not null primary key,
	NAME VARCHAR(250),
	DESCRIPTION VARCHAR(250)
);

CREATE SEQUENCE S_INSTITUTION_TYPE START WITH 1 INCREMENT BY 1;


create table INSTITUTION
(
	INSTITUTION_ID INTEGER not null primary key,
	NAME VARCHAR(250),
	TYPE_ID INTEGER not null,
	ADDRESSLINE1 VARCHAR(250),
	ADDRESSLINE2 VARCHAR(250),
	CITY VARCHAR(25),
	STATE CHAR(2),
	PHONE CHAR(12),
	FAX CHAR(12),
	EMAIL VARCHAR(250),
	CONSTRAINT F_INSTITUTION_TYPE FOREIGN KEY (TYPE_ID) REFERENCES INSTITUTION_TYPE (TYPE_ID)
);

CREATE SEQUENCE S_INSTITUTION START WITH 1 INCREMENT BY 1;


create table STUDENT
(
	STUDENT_ID INTEGER not null primary key,
	STUDENT_NAME VARCHAR(250),
	IDNUMBER NUMERIC not null,
	FIRSTNAME VARCHAR(250),
	LASTNAME VARCHAR(250),
	EMAIL VARCHAR(250),
	MODULENAME VARCHAR(250),
	INSTITUTION_ID INTEGER not null,
	CONSTRAINT F_INSTITUTION FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION (INSTITUTION_ID)
);

CREATE SEQUENCE S_STUDENT START WITH 1 INCREMENT BY 1;



